language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - pypy3

install:
  - pip install -r requirements.txt
  - pip install -t test-requirements.txt
  - pip install wheel

script:
  - flake8 digestive
  - coverage run --branch --source digestive --module py.test --strict tests/
  - python setup.py bdist_wheel
  - pip install dist/digestive*.whl
  - digestive --hashes --recursive --output /tmp/digestive-test-output.yml tests/files
  # grep has a non-zero exit status if no line was matched (expecting both strings to be present)
  - grep random.dd /tmp/digestive-test-output.yml
  - grep 810ec5f2086379f0e8000456dbf2aede8538fbc9d9898835f114c8771ed834b5 /tmp/digestive-test-output.yml

after_success:
  - coveralls
