language: python

python:
  - 3.3
  - 3.4

install:
  - pip install flake8
  - pip install pep8-naming
  - pip install coveralls
  - pip install decorator

script:
  - flake8 --max-line-length=120 digestive
  - coverage run --branch --source digestive -m py.test

after_success:
  - coveralls
