# request a 14.04 build agent
sudo: true
dist: trusty

language: python

python:
  - 3.3
  - 3.4
  - 3.5

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libewf2

install:
  - pip install flake8
  - pip install pep8-naming
  - pip install coveralls
  - pip install wheel
  - pip install decorator
  - pip install PyYAML
  - pip install pysha3

script:
  - flake8 --max-line-length=120 digestive
  - coverage run --branch --source digestive -m py.test
  - python setup.py bdist_wheel
  - pip install dist/digestive*.whl
  - digestive --hashes --recursive --output /tmp/digestive-test-output.yml tests/files
  # grep has a non-zero exit status if no line was matched (expecting both strings to be present)
  - grep random.dd /tmp/digestive-test-output.yml
  - grep 810ec5f2086379f0e8000456dbf2aede8538fbc9d9898835f114c8771ed834b5 /tmp/digestive-test-output.yml

after_success:
  - coveralls
