language: python

python:
  - 3.2
  - 3.3
  - 3.4
  - pypy3

install:
  - pip install flake8
  - pip install coveralls
  - pip install decorator

script:
  - flake8 --max-line-length=120 digestive
  - coverage run --source digestive -m py.test

after_success:
  - coveralls
