name: Test package

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install nox
        run: pip install nox
      - name: Run checks
        run: nox --non-interactive --session check
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', 'pypy-3.7', 'pypy-3.8', 'pypy-3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install nox
        run: pip install nox
      - name: Run tests
        # force nox to use "python", pointing to the version provided by the setup action
        run: nox --non-interactive --force-python python --session test
      - name: Install package
        run: python setup.py install
      - name: Run locally
        run: |
          digestive --hashes --recursive --output /tmp/digestive-test-output.yml tests/files
          grep random.dd /tmp/digestive-test-output.yml
          grep 810ec5f2086379f0e8000456dbf2aede8538fbc9d9898835f114c8771ed834b5 /tmp/digestive-test-output.yml
